config {
  type: "operations",
  schema: "sentiment_analysis",
  hasOutput: true,
  description: "Object table referencing user review JSON files in GCS",
  tags: ["sentiment_analysis", "sources"]
}

CREATE OR REPLACE EXTERNAL TABLE ${self()}
WITH CONNECTION `US.vertex-ai-connection`
OPTIONS (
  object_metadata = 'SIMPLE',
  uris = ['gs://gcloud-tech-showcase-multimodal-data/user-reviews/play-store/flood-it/*.json'],
  max_staleness = INTERVAL 1 HOUR,
  metadata_cache_mode = 'AUTOMATIC'
)